##
## EPITECH PROJECT, 2018
## NETiles / Client
## File description:
## Makefile
##

PROJECT	=	NETiles::Client
NAME	=	../client

SOURCES	=	Main.cpp

################################################################################

include ../utils.make