##
## EPITECH PROJECT, 2018
## NETiles / Server
## File description:
## Makefile
##

PROJECT	=	NETiles::Server
NAME	=	../server

SOURCES	=	Main.cpp

################################################################################

include ../utils.make