##
## EPITECH PROJECT, 2018
## NETiles / Editor
## File description:
## Makefile
##

PROJECT	=	NETiles::Editor
NAME	=	../editor

SOURCES	=	Main.cpp			\
		App.cpp				\
		Display.cpp			\
		Ressources/Manager.cpp		\
		States/Main.cpp			\
		Tiles/Tile.cpp			\
		Tiles/Map.cpp			\
		Tiles/Cursor.cpp		\

################################################################################

include ../utils.make