##
## EPITECH PROJECT, 2018
## NETiles / Editor
## File description:
## Makefile
##

PROJECT	=	NETiles::Editor
NAME	=	../editor

SOURCES	=	Main.cpp

################################################################################

include ../utils.make